### ISSUE TITLE
ClearYu Codex

### ISSUE THREAD

**Issue by Syltan-Adam** [OXOIndustries/TiTS-Public#2]
ClearYu

Manufactured By: Xenogen Biotech

About:
Never one to completely abandon a product line, when **Xenogen discontinued work on Dumbfuck for its unexpected mind-altering side effects,** they transferred much of the research to another department, who came up with ClearYu.

User greif?

**Comment by Tyrn-11** [comment]
What is the issue here? Dumbfuck is an actual in-game item, aquireable from Dr. Badger on Tarkus.
And it's name is not the actual name Xenogen gave it, but how it was called by others due to it's effects.

Once you have unlocked it in your codex, it can be found in the items / illegeal drugs section.

**Comment by Syltan-Adam** [comment]
Ah, excuse me. I thought it was some random shit someone posted. Would it
be called by the professional name eitherway?

**Comment by Tyrn-11** [comment]
The professional name is never given, since the product was never marketed by Xenogen. The information on it's composition was stolen by a hacker however. Therefore, the actual Dumbfuck is an enhanced version of the Xenogen one, likely created by black market scientists.
At least that what I make of the codex entry for Dumbfuck.

**Comment by Syltan-Adam** [comment]
Ah, Then, if this isnt an issue, i'll close this.
